### ISSUE TITLE
Schedule Meeting Window is Blank

### ISSUE THREAD

**Issue by jmcuneo** [flathub/us.zoom.Zoom#364]
I'm using the Flatpak installation of Zoom 5.13.4 on Xubuntu 22.04. The main client works fine, but when I try to pull up the Schedule Meeting window, it appears blank.

![Blank Schedule Meeting window](https://user-images.githubusercontent.com/34037938/212393562-3fc7645a-a022-408f-8c1b-cb58f2209af6.png)

I can get this window to appear if I natively install Zoom's *.deb package for Ubuntu systems, so this is likely a Flatpak error.

**Comment by AndiHofi** [comment]
Exact same issue with Zoom 5.13.4 on Pop_OS 22.04 with Gnome on X11

Not tested yet, if it works with a native installation

**Comment by ntninja** [comment]
Also affects KDE/Kwin on Debian unstable if X11 is forced (using `flatpak run --nosocket=wayland us.zoon.Zoom` or by setting `XDG_CURRENT_DESKTOP=GNOME`). If Wayland is used Zoom instead SegFaults with the following log messages:

> X Error of failed request:  BadWindow (invalid Window parameter)
>  Major opcode of failed request:  15 (X_QueryTree)
>  Resource id in failed request:  0x2400002
>  Serial number of failed request:  7
>  Current serial number in output stream:  7
> QMutex: destroying locked mutex
> zoom was exited due to a handled signal: 11 
> ZoomLauncher exit.

On X11 no related log messages are produced. All of these issues also affect viewing the *Mail* and *Calender* tabs.

Somehow, I  figured this might be related to the use of Zypak and indeed: **Running Zoom with `ZYPAK_ZYGOTE_STRATEGY_SPAWN=0`** (forcing the old pre-Flatpak-1.8.2 mimic strategy) **works around the issue when X11 is used**. On Wayland it still crashes, though.

This should probably be forwarded to the Zypak project: https://github.com/refi64/zypak

**Comment by MisterBoson** [comment]
Same problem for Zoom 5.13.7 in Ubuntu 22.04 with installation via snap or from the official website with a .deb file.

**Comment by AndiHofi** [comment]
Never updated the state, but it has been fixed not long after my last comment here - maybe by the Qt library changes.

**Comment by daghaug** [comment]
Still have this issue in flatpak zoom 5.16.6.382, Fedora 38, Gnome on Wayland

**Comment by rustbuckett** [comment]
Still seeing the issue on Debian 12 with Sway and Zorin-OS with Zorin Desktop. Both using AMD graphics cards.

**Comment by chrisbier** [comment]
Still an issue with PopOS 22.04 and Zoom build 6.1.11 (1545). i3 on X11, Nvidia graphics.

**Comment by serhumanos** [comment]
> ZYPAK_ZYGOTE_STRATEGY_SPAWN=0

this done the job, using Flatpak Zoom v6.2.11 (5069)
thanks!

**Comment by jstebbins** [comment]
Seeing this on Fedora 41 with wayland using flatpak Zoom 6.3.0.5527. 

But can be worked around with
```
flatpak override --env=ZYPAK_ZYGOTE_STRATEGY_SPAWN=0 us.zoom.Zoom
```

**Comment by mike1-proj** [comment]
I got a permission denied message when I tried jstebbins suggestion but on reading around on other suggestions, I uninstalled the flatpack version and went to the zoom downloads center and downloaded the zoom_amd64.deb version and right clicked on it and chose the offered installer method to install it. Bingo! zoom 6.3.6.6315 now runs perfectly! Curiosly, there is no sign of it in the installed apps list. However, its in the internet apps list though and launches fine from there. it has all the connectivity now to the schedule a meeting and calendar entrys which I used to have now. after installing, when you launch it, You may get a message saying zoom is not responding  but just wait a moment and voila it appears!

**Comment by RevJules** [comment]
Having same issue with Elemental OS.  Installed from Appcentre, get permission denied if using Jstebbins workaround above.  downloaded from Zoom site as 'other op system' zoom amd64.deb but still no joy.  Any suggestions gratefully received.

**Comment by RevJules** [comment]
This worked:  https://www.howtogeek.com/how-to-install-zoom-on-linux/

**Comment by paloha** [comment]
Hi, I have the same issue on Ubuntu 24.04.02 with Flatpak Zoom `v.6.3.6.6315`, runtime `org.freedesktop.Platform/x86_64/24.08`.  Doing `sudo flatpak override --env=ZYPAK_ZYGOTE_STRATEGY_SPAWN=0 us.zoom.Zoom`
did not help me. But adding `ZYPAK_ZYGOTE_STRATEGY_SPAWN=0` to Environment variables using FlatSeal did.

**Comment by Lattay** [comment]
Setting `ZYPAK_ZYGOTE_STRATEGY_SPAWN=0` through flatseal with flatpak's zoom 6.3.10.7150 on archlinux fixed the problem for me.

**Comment by Originalme** [comment]
`ZYPAK_ZYGOTE_STRATEGY_SPAWN=0` seems to resolve the issue. Is there a way to build this into the package iteslf so you do not have to manully set it?

**Comment by dakra137** [comment]
Same problem with zoom 7.0.0 on lubuntu 25.04, since upgrading from 6. something

**Comment by grinsted** [comment]
Same problem fedora 44 kde flatpak . ZYPAK_ZYGOTE_STRATEGY_SPAWN=0 does NOT resolve the issue.
